site_name: Gangway Kubernetes configuration generator documentation
site_url: https://numberly.github.io/gangway
repo_url: https://github.com/numberly/gangway

docs_dir: docs/
# exclude_docs: overrides/

copyright: Copyright © 2023 Numberly

theme:
  name: material
  font: false
  # custom_dir: docs/overrides
  # logo:
  #   assets/logo_by_maxicons.png
  palette:
    primary: blue
  features:
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - toc.follow
    - toc.integrate

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/numberly/gangway
      name: gangway on Github

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# nav:
#   - Home: index.md
#   - Getting Started:
#     - getting-started/installation.md
#     - getting-started/quick-start.md
#     - getting-started/philosophy.md
#   - Configuration:
#     - setup/index.md
#     - setup/choosing-the-structure.md
#     - setup/setting-up-languages.md
#     - setup/translating-content.md
#     - setup/controlling-your-builds.md
#     - setup/localizing-navigation.md
#     - setup/using-i18n-context.md
#     - setup/using-alternates.md
#     - setup/upgrading-to-1.md
#     - Plugins Compatibility:
#       - setup/setting-up-material.md
#       - setup/setting-up-search.md
#       - setup/plugins-compatibility.md
#   - Changelog: changelog.md

plugins:
  - search
