apiVersion: v1
data:
  gangway.yaml: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.configuration "context" $ ) | nindent 4 }}
kind: ConfigMap
metadata:
  name: gangway-config
  namespace: {{ .Release.Namespace | quote }}