    cluster_name: "YourCluster"
    authorize_url: "https://example.auth0.com/authorize"  
    token_url: "https://example.auth0.com/oauth/token" 
    client_id: "<your client ID>"
    client_secret: "<your client secret>"
    audience: "https://example.auth0.com/userinfo"
    redirect_url: "https://gangway.yourcluster.com/callback" 
    scopes: ["openid", "profile", "email", "offline_access"] 
    username_claim: "sub"
    email_claim: "email"