    clusterName: "YourCluster"
    authorizeURL: "https://example.auth0.com/authorize"  
    tokenURL: "https://example.auth0.com/oauth/token" 
    clientID: "<your client ID>"
    clientSecret: "<your client secret>"
    audience: "https://example.auth0.com/userinfo"
    redirectURL: "https://gangway.yourcluster.com/callback" 
    scopes: ["openid", "profile", "email", "offline_access"] 
    usernameClaim: "sub"
    emailClaim: "email"