# Example Read Only ClusterRoleBinding
# leveraging the built in default view ClusterRole

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ro-oidc-user # can be called whatever you wish
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group 
    name: readonly # This must match the a group in your OIDC user info
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view 

